### ISSUE TITLE
Consider removing SecureString usage

### ISSUE THREAD

**Issue by shuuryou** [AndreasReitberger/LexOfficeClientSharp#25]
I noticed that the API surface makes extensive use of SecureString for API token handling, which creates some friction points in modern .NET applications. I realize this is rather opinionated, but allow me to provide some context about why I believe this matters:

- Microsoft's own guidance recommends against using SecureString in new development (https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-security-securestring)
- SecureString is effectively legacy as of .NET Core
- In an API client context, the token typically:
  - Starts as a plain string (typically from configuration)
  - Gets converted to SecureString 
  - Gets marshaled back to string for making HTTP requests (https://github.com/AndreasReitberger/CoreSharp/blob/main/source/CoreSharp/Utilities/SecureStringHelper.cs)
  - Exists in process memory as plain text during API calls anyway

If you ever do extensive maintenance on this codebase, could you consider just removing SecureString? This would:
- Reduce unnecessary marshaling overhead
- Simplify integration with modern .NET configuration patterns
- Remove what is basically just ceremonial security theater that doesn't provide actual benefits
- Make the code more approachable for new developers

Or you can close the issue at your discretion. I have no loss or benefit either way.

**Comment by AndreasReitberger** [comment]
Hello @shuuryou 

Thanks for your feedback and pointing out the problem with `SecureStorage`. I will look into this once I find some time.

Feel free to open up a PR if you want to contribute and fix this by your own till that :)
