### ISSUE TITLE
Feature to avoid hitting the Rate Limits

### ISSUE THREAD

**Issue by AlexHolly** [AndreasReitberger/LexOfficeClientSharp#44]
I noticed that there is currently no support for handling Rate Limits. Adding this feature would greatly enhance usability.

see: https://developers.lexoffice.io/docs/#api-rate-limits-hitting-the-rate-limits

**Comment by AndreasReitberger** [comment]
Hi @AlexHolly 
I started to implement a `RateLimitedHandler`. Can you check the draft PR if this is what you thought about?
And if the modifications are working fine for you? Thanks!

**Comment by AndreasReitberger** [comment]
Thanks for the feedback. If you see this again, you can try to set the time here to 2 seconds.
https://github.com/AndreasReitberger/LexOfficeClientSharp/blob/33f29f3864aa0343e4cd1c752ab6eb18b123942c/src/LexOfficeSharpApi/LexOfficeClient.cs#L85

Maybe this solves it completely then.

**Comment by AlexHolly** [comment]
I was able to reproduce it. It can be solved by increasing the `QueueLimit`

            QueueLimit = int.MaxValue,
            ReplenishmentPeriod = TimeSpan.FromSeconds(1.5),
